project 'STFPSIndicatorTest.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
target 'STFPSIndicatorTest' do
pod 'STFPSIndicator', :path => '../', :configurations => ['Debug']
end
